name: Angular CI with Email Notification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2  # Clona los últimos 2 commits

      - name: Check for modified file
        id: check-file
        run: |
          # Verificar si es el primer commit
          if [ $(git rev-list --count HEAD) -eq 1 ]; then
            echo "Primer commit. Todos los archivos son nuevos."
            echo "::set-output name=file_modified::true"
          else
            # Comparar con el commit anterior
            git diff --name-only HEAD^ HEAD > modified_files.txt
            if grep -q "src/app/my-file.ts" modified_files.txt; then
              echo "::set-output name=file_modified::true"
            else
              echo "::set-output name=file_modified::false"
            fi
          fi

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: npm install
      - run: npm run build -- --prod
      - run: npm test
      - run: npm run e2e

      - name: Send email notification
        if: steps.check-file.outputs.file_modified == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "¡Alerta! Cambios en el archivo importante"
          body: |
            ¡Hola equipo!

            El archivo `src/app/my-file.ts` ha sido modificado en el último commit.
            Detalles del cambio:
            - **Mensaje del commit:** ${{ github.event.head_commit.message }}
            - **Hash del commit:** ${{ github.sha }}
            - **Estado del workflow:** ${{ job.status }}

            Revisa los cambios aquí: https://github.com/antonioDiaz04/proyecto-ATR-frontend/commit/${{ github.sha }}

            ¡Saludos!
            El equipo de DevOps
          to: ${{ secrets.EMAIL_RECIPIENT }}
          from: ${{ secrets.EMAIL_USERNAME }}
          content_type: text/plain